import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: { translation: { dashboard: "Dashboard", market: "Market", search: "Search", watchlist: "Watchlist", ai: "AI", settings: "Settings", login: "Login", signup: "Sign Up", logout: "Logout", sign_out: "Sign Out", security: "Security", biometrics: "Biometrics", pin_lock: "PIN Lock", language: "Language", theme: "Theme", dark: "Dark", light: "Light", real_time_stocks: "Real-time Stocks", my_portfolio: "My Portfolio", total_value: "Total Value", profit_loss: "Profit/Loss", ask_ai: "Ask AI Assistant", voice_command: "Voice Command", preferences: "Preferences", notifications: "Notifications", price_alerts: "Price Alerts", market_open_close: "Market Open / Close", breaking_news: "Breaking News", account: "Account", email: "Email", two_factor_auth: "Two-Factor Auth", change_password: "Change Password", data_privacy: "Data & Privacy", data_usage: "Data Usage", privacy_policy: "Privacy Policy", terms_of_service: "Terms of Service", about: "About", version: "Version", rate_the_app: "Rate the App", send_feedback: "Send Feedback", pro_trader: "Pro Trader", global_markets: "GLOBAL MARKETS — 24/7", us_indices: "US INDICES", top_gainers: "Top Gainers", top_losers: "Top Losers", see_all: "See all", market_closed: "US Market Closed", market_open: "US Market Open", edit_profile: "Edit Profile", save: "Save", cancel: "Cancel", delete_account: "Delete Account" } },
  te: { translation: { dashboard: "డ్యాష్‌బోర్డ్", market: "మార్కెట్", search: "శోధన", watchlist: "వాచ్‌లిస్ట్", ai: "AI", settings: "సెట్టింగులు", login: "లాగిన్", signup: "సైన్ అప్", logout: "లాగ్ అవుట్", sign_out: "సైన్ అవుట్", security: "భద్రత", biometrics: "బయోమెట్రిక్స్", pin_lock: "పిన్ లాక్", language: "భాష", theme: "థీమ్", dark: "డార్క్", light: "లైట్", real_time_stocks: "రియల్ టైమ్ స్టాక్స్", my_portfolio: "నా పోర్ట్‌ఫోలియో", total_value: "మొత్తం విలువ", profit_loss: "లాభం/నష్టం", ask_ai: "AI అసిస్టెంట్‌ని అడగండి", voice_command: "వాయిస్ కమాండ్", preferences: "ప్రాధాన్యతలు", notifications: "నోటిఫിക്കేషన్లు", price_alerts: "ధర హెచ్చరికలు", market_open_close: "మార్కెట్ ఓపెన్ / క్లోజ్", breaking_news: "బ్రేకింగ్ న్యూస్", account: "ఖాతా", email: "ఈమెయిల్", two_factor_auth: "టూ-ఫాక్టర్ ఆథ్", change_password: "పాస్‌వర్డ్ మార్చండి", data_privacy: "డేటా & గోప్యత", data_usage: "డేటా వినియోగం", privacy_policy: "గోప్యతా విధానం", terms_of_service: "సేవా నిబంధనెలు", about: "గురించి", version: "వెర్షన్", rate_the_app: "యాప్‌ను రేట్ చేయండి", send_feedback: "అభిప్రాయాన్ని పంపండి", pro_trader: "ప్రో ట్రేడర్", global_markets: "గ్లోబల్ మార్కెట్లు — 24/7", us_indices: "US సూచీలు", top_gainers: "టాప్ గెయినర్స్", top_losers: "టాప్ లూజర్స్", see_all: "అన్నీ చూడండి", market_closed: "US మార్కెట్ మూసివేయబడింది", market_open: "US మార్కెట్ తెరిచి ఉంది", edit_profile: "ప్రొఫైల్ సవరించండి", save: "సేవ్", cancel: "రద్దు", delete_account: "ఖాతాను తొలగించు" } },
  hi: { translation: { dashboard: "डैशबोर्ड", market: "बाजार", search: "खोज", watchlist: "वॉचलिस्ट", ai: "AI", settings: "सेटिंग्स", login: "लॉगिन", signup: "साइन अप", logout: "लॉगआउट", sign_out: "साइन आउट", security: "सुरक्षा", biometrics: "बायोमेट्रिक्स", pin_lock: "पिन लॉक", language: "भाषा", theme: "थीम", dark: "डार्क", light: "लाइट", real_time_stocks: "रियल-टाइम स्टॉक", my_portfolio: "मेरा पोर्टफोलियो", total_value: "कुल मूल्य", profit_loss: "लाभ/हानि", ask_ai: "AI सहायक से पूछें", voice_command: "वॉयस कमांड", preferences: "प्राथमिकताएं", notifications: "सूचनाएं", price_alerts: "मूल्य अलर्ट", market_open_close: "बाजार खुला / बंद", breaking_news: "ताज़ा खबर", account: "खाता", email: "ईमेल", two_factor_auth: "टू-फैक्टर ऑथ", change_password: "पासवर्ड बदलें", data_privacy: "डेटा और गोपनीयता", data_usage: "डेटा उपयोग", privacy_policy: "गोपनीयता नीति", terms_of_service: "सेवा की शर्तें", about: "के बारे में", version: "संस्करण", rate_the_app: "ऐप को रेट करें", send_feedback: "प्रतिक्रिया भेजें", pro_trader: "प्रो ट्रेडर", global_markets: "वैश्विक बाजार — 24/7", us_indices: "अमेरिकी सूचकांक", top_gainers: "शीर्ष लाभकर्ता", top_losers: "शीर्ष हारने वाले", see_all: "सभी देखें", market_closed: "अमेरिकी बाजार बंद", market_open: "अमेरिकी बाजार खुला", edit_profile: "प्रोफ़ाइल संपादित करें", save: "सहेजें", cancel: "रद्द करें", delete_account: "खाता हटाएं" } },
  es: { translation: { dashboard: "Tablero", market: "Mercado", search: "Buscar", watchlist: "Lista de seguimiento", ai: "IA", settings: "Ajustes", login: "Iniciar sesión", signup: "Registrarse", logout: "Cerrar sesión", sign_out: "Desconectarse", security: "Seguridad", biometrics: "Biometría", pin_lock: "Bloqueo de PIN", language: "Idioma", theme: "Tema", dark: "Oscuro", light: "Claro", real_time_stocks: "Acciones en tiempo real", my_portfolio: "Mi cartera", total_value: "Valor total", profit_loss: "Ganancia/Pérdida", ask_ai: "Preguntar al asistente de IA", voice_command: "Comando de voz", preferences: "Preferencias", notifications: "Notificaciones", price_alerts: "Alertas de precios", market_open_close: "Apertura / Cierre de mercado", breaking_news: "Noticias de última hora", account: "Cuenta", email: "Correo electrónico", two_factor_auth: "Autenticación de dos factores", change_password: "Cambiar contraseña", data_privacy: "Datos y privacidad", data_usage: "Uso de datos", privacy_policy: "Política de privacidad", terms_of_service: "Términos de servicio", about: "Acerca de", version: "Versión", rate_the_app: "Calificar la aplicación", send_feedback: "Enviar comentarios", pro_trader: "Operador Pro", global_markets: "MERCADOS GLOBALES — 24/7", us_indices: "ÍNDICES DE EE. UU.", top_gainers: "Principales ganadores", top_losers: "Principales perdedores", see_all: "Ver todo", market_closed: "Mercado de EE. UU. cerrado", market_open: "Mercado de EE. UU. abierto", edit_profile: "Editar perfil", save: "Guardar", cancel: "Cancelar", delete_account: "Eliminar cuenta" } },
  fr: { translation: { dashboard: "Tableau de bord", market: "Marché", search: "Rechercher", watchlist: "Liste de surveillance", ai: "IA", settings: "Paramètres", logout: "Déconnexion", sign_out: "Se déconnecter", security: "Sécurité", language: "Langue", theme: "Thème", dark: "Sombre", light: "Clair", edit_profile: "Modifier le profil", save: "Enregistrer", cancel: "Annuler" } },
  de: { translation: { dashboard: "Dashboard", market: "Markt", search: "Suche", watchlist: "Watchlist", ai: "KI", settings: "Einstellungen", logout: "Abmelden", sign_out: "Abmelden", security: "Sicherheit", language: "Sprache", theme: "Thema", dark: "Dunkel", light: "Hell", edit_profile: "Profil bearbeiten", save: "Speichern", cancel: "Abbrechen" } },
  zh: { translation: { dashboard: "仪表板", market: "市场", search: "搜索", watchlist: "自选股", ai: "人工智能", settings: "设置", logout: "登出", sign_out: "退出登录", security: "安全", language: "语言", theme: "主题", dark: "深色", light: "浅色", edit_profile: "编辑资料", save: "保存", cancel: "取消" } },
  ja: { translation: { dashboard: "ダッシュボード", market: "市場", search: "検索", watchlist: "ウォッチリスト", ai: "AI", settings: "設定", logout: "ログアウト", sign_out: "サインアウト", security: "セキュリティ", language: "言語", theme: "テーマ", dark: "ダーク", light: "ライト", edit_profile: "プロフィールを編集", save: "保存", cancel: "キャンセル" } },
  ko: { translation: { dashboard: "대시보드", market: "시장", search: "검색", watchlist: "관심목록", ai: "AI", settings: "설정", logout: "로그아웃", sign_out: "로그아웃", security: "보안", language: "언어", theme: "테มา", dark: "다크", light: "라이트", edit_profile: "프로필 수정", save: "저장", cancel: "취소" } },
  ar: { translation: { dashboard: "لوحة القيادة", market: "السوق", search: "بحث", watchlist: "قائمة المراقبة", ai: "الذكاء الاصطناعي", settings: "الإعدادات", logout: "تسجيل الخروج", sign_out: "تسجيل الخروج", security: "الأمان", language: "اللغة", theme: "المظهر", dark: "داكن", light: "فاتح", edit_profile: "تعديل الملف الشخصي", save: "حفظ", cancel: "إلغاء" } },
  ru: { translation: { dashboard: "Панель", market: "Рынок", search: "Поиск", watchlist: "Список наблюдения", ai: "ИИ", settings: "Настройки", logout: "Выход", sign_out: "Выйти", security: "Безопасность", language: "Язык", theme: "Тема", dark: "Темная", light: "Светлая", edit_profile: "Редактировать профиль", save: "Сохранить", cancel: "Отмена" } },
  pt: { translation: { dashboard: "Painel", market: "Mercado", search: "Buscar", watchlist: "Lista de observação", ai: "IA", settings: "Configurações", logout: "Sair", sign_out: "Sair", security: "Segurança", language: "Idioma", theme: "Tema", dark: "Escuro", light: "Claro", edit_profile: "Editar perfil", save: "Salvar", cancel: "Cancelar" } },
  it: { translation: { dashboard: "Dashboard", market: "Mercato", search: "Cerca", watchlist: "Watchlist", ai: "IA", settings: "Impostazioni", logout: "Esci", sign_out: "Disconnetti", security: "Sicurezza", language: "Lingua", theme: "Tema", dark: "Scuro", light: "Chiaro", edit_profile: "Modifica profilo", save: "Salva", cancel: "Annulla" } },
  tr: { translation: { dashboard: "Panel", market: "Piyasa", search: "Ara", watchlist: "İzleme Listesi", ai: "Yapay Zeka", settings: "Ayarlar", logout: "Çıkış Yap", sign_out: "Oturumu Kapat", security: "Güvenlik", language: "Dil", theme: "Tema", dark: "Koyu", light: "Açık", edit_profile: "Profili Düzenle", save: "Kaydet", cancel: "İptal" } },
  id: { translation: { dashboard: "Dasbor", market: "Pasar", search: "Cari", watchlist: "Daftar Pantau", ai: "AI", settings: "Pengaturan", logout: "Keluar", sign_out: "Keluar", security: "Keamanan", language: "Bahasa", theme: "Tema", dark: "Gelap", light: "Terang", edit_profile: "Edit Profil", save: "Simpan", cancel: "Batal" } },
  th: { translation: { dashboard: "แดชบอร์ด", market: "ตลาด", search: "ค้นหา", watchlist: "รายการเฝ้าดู", ai: "AI", settings: "การตั้งค่า", logout: "ออกจากระบบ", sign_out: "ออกจากระบบ", security: "ความปลอดภัย", language: "ภาษา", theme: "ธีม", dark: "มืด", light: "สว่าง", edit_profile: "แก้ไขโปรไฟล์", save: "บันทึก", cancel: "ยกเลิก" } },
  vi: { translation: { dashboard: "Bảng điều khiển", market: "Thị trường", search: "Tìm kiếm", watchlist: "Danh sách theo dõi", ai: "AI", settings: "Cài đặt", logout: "Đăng xuất", sign_out: "Đăng xuất", security: "Bảo mật", language: "Ngôn ngữ", theme: "Giao diện", dark: "Tối", light: "Sáng", edit_profile: "Chỉnh sửa hồ sơ", save: "Lưu", cancel: "Hủy" } },
  bn: { translation: { dashboard: "ড্যাশবোর্ড", market: "বাজার", search: "অনুসন্ধান", watchlist: "ওয়াচলিস্ট", ai: "এআই", settings: "সেটিংস", logout: "লগ আউট", sign_out: "লগ আউট", security: "নিরাপত্তা", language: "ভাষা", theme: "থিম", dark: "ডার্ক", light: "লাইট", edit_profile: "প্রোফাইল সম্পাদনা", save: "সংরক্ষণ", cancel: "বাতিল" } },
  ur: { translation: { dashboard: "ڈیش بورڈ", market: "مارکیٹ", search: "تلاش", watchlist: "واچ لسٹ", ai: "اے آئی", settings: "ترتیبات", logout: "لاگ آؤٹ", sign_out: "لاگ آؤٹ", security: "سیکیورٹی", language: "زبان", theme: "تھیم", dark: "ڈارک", light: "لائٹ", edit_profile: "پروفائل ایڈٹ کریں", save: "محفوظ کریں", cancel: "منسوخ کریں" } },
  ta: { translation: { dashboard: "டாஷ்போர்டு", market: "சந்தை", search: "தேடல்", watchlist: "வாட்ச்லிสต์", ai: "AI", settings: "அமைப்புகள்", logout: "வெளியேறு", sign_out: "வெளியேறு", security: "பாதுகாப்பு", language: "மொழி", theme: "தீம்", dark: "டார்க்", light: "லைట్", edit_profile: "சுயவிவரத்தைத் திருத்து", save: "சேமி", cancel: "ரத்து" } },
  ml: { translation: { dashboard: "ഡാഷ്‌ബോർഡ്", market: "മാർക്കറ്റ്", search: "തിരയുക", watchlist: "വാച്ച്‌ലിസ്റ്റ്", ai: "AI", settings: "ക്രമീകരണങ്ങൾ", logout: "ലോഗ് ഔട്ട്", sign_out: "ലോഗ് ഔട്ട്", security: "സുരക്ഷ", language: "ഭാഷ", theme: "തീം", dark: "ഡാർക്ക്", light: "ലൈറ്റ്", edit_profile: "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക", save: "സേവ് ചെയ്യുക", cancel: "റദ്ദാക്കുക" } },
  kn: { translation: { dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", market: "ಮಾರುಕಟ್ಟೆ", search: "ಹುಡುಕಾಟ", watchlist: "ವಾಚ್‌ಲಿಸ್ಟ್", ai: "AI", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", logout: "ಲಾಗ್ ಔಟ್", sign_out: "ಲಾಗ್ ಔಟ್", security: "ಭದ್ರತೆ", language: "ಭಾಷ", theme: "ಥೀಮ್", dark: "ಡಾರ್ಕ್", light: "ಲೈಟ್", edit_profile: "ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ", save: "ಉಳಿಸಿ", cancel: "ರದ್ದುಮಾಡಿ" } }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: "en",
    fallbackLng: "en",
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
